/**
 * GraphQL `extensions.code` values. Catalog: docs/design-reference.md, section 7.5.
 */
export const ErrorCode = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ORG_SLUG_TAKEN: 'ORG_SLUG_TAKEN',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  JOIN_REQUEST_PENDING: 'JOIN_REQUEST_PENDING',
  JOIN_REQUEST_NOT_PENDING: 'JOIN_REQUEST_NOT_PENDING',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_ORDER: 'INVALID_ORDER',
  INVALID_MENTION: 'INVALID_MENTION',
  QUERY_TOO_COMPLEX: 'QUERY_TOO_COMPLEX',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  PROJECT_KEY_TAKEN: 'PROJECT_KEY_TAKEN',
  STATUS_NOT_IN_PROJECT: 'STATUS_NOT_IN_PROJECT',
  STATUS_ARCHIVED: 'STATUS_ARCHIVED',
  STATUS_IN_USE: 'STATUS_IN_USE',
  STATUS_NAME_TAKEN: 'STATUS_NAME_TAKEN',
  STATUS_LIMIT_REACHED: 'STATUS_LIMIT_REACHED',
  DEFAULT_STATUS_INVALID: 'DEFAULT_STATUS_INVALID',
  ASSIGNEE_NOT_MEMBER: 'ASSIGNEE_NOT_MEMBER',
  ASSIGNEE_INACTIVE: 'ASSIGNEE_INACTIVE',
  LAST_OWNER: 'LAST_OWNER',
  MEMBER_NOT_ACTIVE: 'MEMBER_NOT_ACTIVE',
  LABEL_NAME_TAKEN: 'LABEL_NAME_TAKEN',
  LABEL_ARCHIVED: 'LABEL_ARCHIVED',
  LABEL_LIMIT_REACHED: 'LABEL_LIMIT_REACHED',
  TASK_ARCHIVED: 'TASK_ARCHIVED',
  RANK_CONFLICT: 'RANK_CONFLICT',
  DERIVED_COLUMN_WRITE: 'DERIVED_COLUMN_WRITE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
